### ISSUE TITLE
Cannot compile "fatal error: hs_common.h: No such file or directory"

### ISSUE THREAD

**Issue by CoNFiDeNTHaKaN** [freenode/ircd-seven#154] opened 2019-02-27 12:12 UTC
Hi, 

I was facing "fatal error: hs_common.h: No such file or directory" error message when i try to compile ircd-seven on Ubuntu 18.10.

Solution:
You must install libhyperscan-dev  and pkg-config to get rid of it!

sudo apt-get install libhyperscan-dev pkg-config

Special Thanks to @mquin  for the valuable help. ( staff of freenode )

**Comment by thecodezero** [comment] 2019-03-23 19:11
Hi, this issue must be closed, and this solution should be in-turn be added to other related pull requests about this error.

**Comment by ilbelkyr** [comment] 2019-03-26 02:22
The `--disable-hyperscan` configure flag is supposed to avoid this issue, but currently doesn't.

Closing as duplicate of #153.

**Closed by ilbelkyr** 2019-03-26 02:22 UTC
Labels: duplicate
